### ISSUE TITLE
All videos muted | Unable to change volume

### ISSUE THREAD

**Issue by AugusDogus** [scavet64/TikTokVolumeSlider#1]
On all videos I am getting the following output in the console
```
transformed to 0 using slider: null
```

I'm able to click and hold the volume slider on the video controls and it will move back and forth between the selected volume level and 0.

Manually setting the Local Storage key "customVolume" to 0.4 results in the same behavior but with this output
```
0 transformed to 0 using slider: 0.4
```

**Comment by scavet64** [comment]
@AugusDogus  Hey thanks for letting me know. For whatever reason I can't seem to reproduce this issue on my end, but I just pushed up a new version that hopefully will address the it
